import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HealSyncNavbar from "./component/Navbar";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <Navbar></Navbar>
        {children}
        <Footer></Footer>
<ToastContainer position="top-right" autoClose={3000} theme="colored" />
        </body>
    </html>
  );
}
